var1: Try Me!

string-values:
  
  no-quote: \t\t\tHello World!\n
  
  single-quote: '\t\t\tHello World!\n'
  
  #allow to use escapes characters
  double-quote: "\t\t\tHello World!\n"
  
  double-quote2: "{{ var1 }}\\backslashes\\are\\also\\special\\characters"
  
  #include newlines and tailing spaces
  literal-block-scalar: |
    1st line
    2nd line
    3rd line and spaces after me      
    
  #fold newlines to spaces
  folded-block-scalar: >
    1st line
    2nd line
    3rd line and spaces after me
    
  unicode: "\u7e41\u9ad4\u4e2d\u6587\ud55c\uad6d\uc5b4"
  
list-values:
  sample1:
   - item 1
   - item 2
   - item 3
  sample2: [item A, item B, item C]
  sample3: item 7, item 8, item 9
  sample-4: >
    item 5,
    item 6,
    item 7